### ISSUE TITLE
Move repo to mozart organization

### ISSUE THREAD

**Issue by rkoeninger** [rkoeninger/sublime-oz#2]
@layus 

[Opened PR](https://github.com/wbond/package_control_channel/pull/7258) to `package_control_channel` to change location of this repo to mozart org.

I'm waiting until that PR is merged as PRs to `package_control_channel` can take a while to get merged and want to minimize the length of time links could be broken.

**Comment by rkoeninger** [comment]
@layus Repo has been transferred: https://github.com/mozart/sublime-oz

**Comment by layus** [comment]
Nice! Welcome in the mozart-oz community ;-)
