### ISSUE TITLE
[Question] How to run Oz ?

### ISSUE THREAD

**Issue by lsonnino** [rkoeninger/sublime-oz#4]
Hi,
I tried to install and run Oz in Sublime Text 3.1.1. When I type in some Oz code, it is recognised a Oz and behave as it should normally do but I was not able to display anything.

**To reproduce my problem**
1. I created a simple ```.oz``` file containing ```{Browse 6}```
2. I selected the line and I selected the ```oz > Feed Section``` menu
<img width="752" alt="screenshot 2018-11-28 at 13 59 39" src="https://user-images.githubusercontent.com/30297828/49163262-fb001f80-f32c-11e8-89ac-ad05c0dca37d.png">

but nothing happened.

Is there a step I am missing ?
Thanks in advance

**Comment by rkoeninger** [comment]
Do you have mozart installed and included in your PATH? Make sure the `ozengine` binary is available from the command prompt.

**Comment by lsonnino** [comment]
I have Mozart and Aquamacs installed. Is there a way to somehow *link* the Oz included in Mozart so that I do not have to install to many packages on my computer ?

**Comment by lsonnino** [comment]
The command ```ozengine``` gives ```-bash: ozengine: command not found```

**Comment by rkoeninger** [comment]
Where is Mozart installed? I assume that `.../Mozart/bin` is not in your PATH variable.

I don't know if there's a dialog for it in macOS, but in Linux, updating your PATH involves editing `~/.bashrc` and opening a new terminal.

**Comment by rkoeninger** [comment]
I'm assuming this is working now. Closing.
